### ISSUE TITLE
Data not saved after inital creation

### ISSUE THREAD

**Issue by dschere** [cr0hn/CodernityDB3#3]
On the first run everything is fine.
After the second run I can see the data is in the database but get fails.

I tried this code on CodernityDB (python 2.7 and it works).
# !/usr/bin/env python3

from CodernityDB3.database import Database
from CodernityDB3.hash_index import HashIndex
import os

class WithXIndex(HashIndex):

```
def __init__(self, *args, **kwargs):
    kwargs['key_format'] = 'I'
    super(WithXIndex, self).__init__(*args, **kwargs)

def make_key_value(self, data):
    a_val = data.get("x")
    if a_val is not None:
        return a_val, None
    return None

def make_key(self, key):
    return key
```

class WithYIndex(HashIndex):

```
def __init__(self, *args, **kwargs):
    kwargs['key_format'] = 'I'
    super(WithYIndex, self).__init__(*args, **kwargs)

def make_key_value(self, data):
    a_val = data.get("y")
    if a_val is not None:
        return a_val, None
    return None

def make_key(self, key):
    return key
```

def main():
    db = Database('/tmp/tut24')
    if not os.access('/tmp/tut24',os.F_OK): 
        db.create()
        x_ind = WithXIndex(db.path, 'x')
        y_ind = WithYIndex(db.path, 'y')
        db.add_index(x_ind)
        db.add_index(y_ind)

```
    for x in range(100):
        db.insert(dict(x=x))

    for y in range(100):
        db.insert(dict(y=y))
else:
    db.open() 
    for curr in db.all('x'):
        print( curr )


print( db.get('x', 10, with_doc=True) )
print( db.get('y', 20, with_doc=True) )

db.close()
```

if **name** == '**main**':
    main()

**Comment by dschere** [comment]
Trying to deal with this editor and paste in code.

**Comment by vesellov** [comment]
I started PR where most issues suppose to be fixed.

**Comment by cr0hn** [comment]
@vesellov this issue could be closed with your PR?

**Comment by vesellov** [comment]
I just found another issue with `hash()` method in `hash_index.py` : https://github.com/cr0hn/CodernityDB3/blob/master/CodernityDB3/hash_index.py#L234

 ... spent few days debugging...    in Python3 they added salt to hash() method ... so `_calculate_position()` method is broken at the moment. I am testing my fix and will start a PR soon

**Comment by vesellov** [comment]
I think this is the root cause of that issue

**Comment by vesellov** [comment]
starter a PR

**Comment by cr0hn** [comment]
Nice! thanks. I have not much time to maintain this project. If you want to be maintainer, you are welcome

**Comment by vesellov** [comment]
yes. i can. thanks @cr0hn

**Comment by vesellov** [comment]
We can close that issue, I believe.
